export const cs001 = [
  {
    id: 1,
    text: 'What does CPL stand for?',
    options: [
      'Certified Programming Language',
      'Computer Proficiency License',
      'Computer Personal Learning',
      'Central Processing Logic',
    ],
    correct: 1,
  },
  {
    id: 2,
    text: 'Which of the following is an input device?',
    options: ['Monitor', 'Printer', 'Keyboard', 'Speaker'],
    correct: 2,
  },
  {
    id: 3,
    text: 'Which device is used to produce output in soft copy form?',
    options: ['Monitor', 'Printer', 'Floppy Disk', 'RAM'],
    correct: 0,
  },
  {
    id: 4,
    text: 'Which of these is a primary storage device?',
    options: ['RAM', 'CD-ROM', 'USB Drive', 'Hard Disk'],
    correct: 0,
  },
  {
    id: 5,
    text: 'Which component is considered the "brain" of the computer?',
    options: ['RAM', 'Monitor', 'CPU', 'Motherboard'],
    correct: 2,
  },
  {
    id: 6,
    text: 'What is the purpose of an operating system?',
    options: [
      'Hardware management',
      'Text editing',
      'Drawing graphics',
      'Connecting to the internet',
    ],
    correct: 0,
  },
  {
    id: 7,
    text: 'Which of the following is NOT a type of output device?',
    options: ['Printer', 'Monitor', 'Scanner', 'Speakers'],
    correct: 2,
  },
  {
    id: 8,
    text: 'Which file extension is typically associated with Word documents?',
    options: ['.txt', '.doc', '.jpg', '.xls'],
    correct: 1,
  },
  {
    id: 9,
    text: 'Which key is used to refresh a web page?',
    options: ['F1', 'F5', 'Ctrl + R', 'Shift + F5'],
    correct: 1,
  },
  {
    id: 10,
    text: 'What type of software is MS Excel?',
    options: ['Word Processor', 'Spreadsheet', 'Database', 'Operating System'],
    correct: 1,
  },
  {
    id: 11,
    text: 'What does RAM stand for?',
    options: [
      'Read Access Memory',
      'Random Access Memory',
      'Real Allocation Memory',
      'Remote Application Management',
    ],
    correct: 1,
  },
  {
    id: 12,
    text: 'Which key is used to delete the character to the left of the cursor?',
    options: ['Delete', 'Esc', 'Backspace', 'Insert'],
    correct: 2,
  },
  {
    id: 13,
    text: 'Which is NOT an example of secondary storage?',
    options: ['Floppy Disk', 'Hard Disk', 'RAM', 'CD-ROM'],
    correct: 2,
  },
  {
    id: 14,
    text: 'Which component allows the CPU to communicate with other hardware?',
    options: ['RAM', 'Motherboard', 'Power Supply', 'Monitor'],
    correct: 1,
  },
  {
    id: 15,
    text: 'Which device is used to capture images and input them into a computer?',
    options: ['Printer', 'Monitor', 'Scanner', 'Speaker'],
    correct: 2,
  },
  {
    id: 16,
    text: 'Which software allows for creating and managing slides for presentations?',
    options: ['MS Word', 'MS Excel', 'MS PowerPoint', 'MS Access'],
    correct: 2,
  },
  {
    id: 17,
    text: 'Which of the following is an optical storage device?',
    options: ['RAM', 'Floppy Disk', 'CD-ROM', 'Hard Disk'],
    correct: 2,
  },
  {
    id: 18,
    text: 'What does URL stand for?',
    options: [
      'Universal Resource Link',
      'Uniform Resource Locator',
      'Unified Resource Language',
      'Uniform Research Library',
    ],
    correct: 1,
  },
  {
    id: 19,
    text: 'Which key is used to open the Start menu in Windows?',
    options: ['Ctrl', 'Alt', 'Windows Key', 'Shift'],
    correct: 2,
  },
  {
    id: 20,
    text: 'What type of software is antivirus software?',
    options: [
      'System Software',
      'Application Software',
      'Utility Software',
      'Device Driver',
    ],
    correct: 2,
  },
  {
    id: 21,
    text: 'Which storage device is non-volatile and retains data even after power is turned off?',
    options: ['RAM', 'ROM', 'Cache', 'Register'],
    correct: 1,
  },
  {
    id: 22,
    text: 'Which of the following is NOT a type of computer?',
    options: ['Supercomputer', 'Mainframe', 'Microcomputer', 'Web browser'],
    correct: 3,
  },
  {
    id: 23,
    text: 'Which device is used to record sound into a computer?',
    options: ['Scanner', 'Microphone', 'Speaker', 'Monitor'],
    correct: 1,
  },
  {
    id: 24,
    text: 'Which protocol is used for sending emails?',
    options: ['HTTP', 'FTP', 'SMTP', 'POP3'],
    correct: 2,
  },
  {
    id: 25,
    text: 'Which is NOT an example of hardware?',
    options: ['CPU', 'Mouse', 'MS Word', 'Monitor'],
    correct: 2,
  },
  {
    id: 26,
    text: 'Which device displays visual output from the computer?',
    options: ['Printer', 'Monitor', 'Keyboard', 'Mouse'],
    correct: 1,
  },
  {
    id: 27,
    text: 'What is the primary function of a router?',
    options: [
      'Store data',
      'Process input',
      'Direct network traffic',
      'Display images',
    ],
    correct: 2,
  },
  {
    id: 28,
    text: 'Which software is used to manage databases?',
    options: ['MS Excel', 'MS Access', 'MS PowerPoint', 'Windows'],
    correct: 1,
  },
  {
    id: 29,
    text: 'Which of the following is an example of application software?',
    options: ['RAM', 'CPU', 'MS Word', 'BIOS'],
    correct: 2,
  },
  {
    id: 30,
    text: 'What is the shortcut key to cut selected text?',
    options: ['Ctrl + C', 'Ctrl + X', 'Ctrl + V', 'Ctrl + P'],
    correct: 1,
  },
  {
    id: 31,
    text: 'Which of the following is a web browser?',
    options: ['Google Chrome', 'MS Word', 'Excel', 'PowerPoint'],
    correct: 0,
  },
  {
    id: 32,
    text: 'Which protocol is used for secure data transfer over the web?',
    options: ['HTTP', 'HTTPS', 'FTP', 'SMTP'],
    correct: 1,
  },
  {
    id: 33,
    text: 'What does HTML stand for?',
    options: [
      'HyperText Markup Language',
      'HighText Machine Learning',
      'HyperTool Management Language',
      'HyperTransfer Markup Language',
    ],
    correct: 0,
  },
  {
    id: 34,
    text: 'Which device is used for video conferencing?',
    options: ['Printer', 'Scanner', 'Webcam', 'Speaker'],
    correct: 2,
  },
  {
    id: 35,
    text: 'Which key combination is used to paste copied text?',
    options: ['Ctrl + X', 'Ctrl + V', 'Ctrl + C', 'Ctrl + P'],
    correct: 1,
  },
  {
    id: 36,
    text: 'What is the primary purpose of an IP address?',
    options: [
      'Identify a computer on a network',
      'Store data',
      'Monitor CPU temperature',
      'Print documents',
    ],
    correct: 0,
  },
  {
    id: 37,
    text: 'Which of the following is an example of cloud storage?',
    options: ['Hard Disk', 'Dropbox', 'RAM', 'Flash Drive'],
    correct: 1,
  },
  {
    id: 38,
    text: 'Which device helps in converting digital signals to analog for telephone lines?',
    options: ['Router', 'Switch', 'Modem', 'Printer'],
    correct: 2,
  },
  {
    id: 39,
    text: 'What does GUI stand for?',
    options: [
      'Graphical User Interface',
      'General User Instruction',
      'Global Uniform Interface',
      'Graph Use Interaction',
    ],
    correct: 0,
  },
  {
    id: 40,
    text: 'Which unit measures the speed of a computer processor?',
    options: ['GHz', 'GB', 'MB', 'TB'],
    correct: 0,
  },
  {
    id: 41,
    text: 'Which software is used to create spreadsheets?',
    options: ['MS Word', 'MS Excel', 'MS PowerPoint', 'Notepad'],
    correct: 1,
  },
  {
    id: 42,
    text: 'Which of the following is NOT a programming language?',
    options: ['Python', 'Java', 'HTML', 'Windows'],
    correct: 3,
  },
  {
    id: 43,
    text: 'What does IP stand for in networking?',
    options: [
      'Internet Protocol',
      'Internal Program',
      'Initial Process',
      'Input Protocol',
    ],
    correct: 0,
  },
  {
    id: 44,
    text: 'Which of the following is used to permanently store data?',
    options: ['RAM', 'Cache', 'Hard Disk', 'Register'],
    correct: 2,
  },
  {
    id: 45,
    text: 'Which is the main circuit board in a computer?',
    options: ['Power Supply', 'Motherboard', 'Monitor', 'Keyboard'],
    correct: 1,
  },
  {
    id: 46,
    text: 'What does LAN stand for?',
    options: [
      'Large Area Network',
      'Local Area Network',
      'Light Access Node',
      'Logical Area Network',
    ],
    correct: 1,
  },
  {
    id: 47,
    text: 'Which device is essential for connecting to the internet?',
    options: ['Printer', 'Monitor', 'Router', 'Scanner'],
    correct: 2,
  },
  {
    id: 48,
    text: 'Which part of the computer executes instructions from software?',
    options: ['RAM', 'Hard Disk', 'CPU', 'Monitor'],
    correct: 2,
  },
  {
    id: 49,
    text: 'Which is the smallest unit of data in a computer?',
    options: ['Bit', 'Byte', 'Kilobyte', 'Megabyte'],
    correct: 0,
  },
  {
    id: 50,
    text: 'Which of the following is an example of a search engine?',
    options: ['Google', 'Windows', 'Linux', 'Firefox'],
    correct: 0,
  },
];
