export const cs101 = [
  {
    id: 1,
    text: 'Who is known as the father of computing?',
    options: ['Bill Gates', 'Steve Jobs', 'Charles Babbage', 'Alan Turing'],
    correct: 2,
  },
  {
    id: 2,
    text: "Which component is considered the 'brain' of the computer?",
    options: ['RAM', 'Hard Drive', 'CPU', 'Power Supply'],
    correct: 2,
  },
  {
    id: 3,
    text: 'What is the smallest unit of data in a computer?',
    options: ['Bit', 'Byte', 'Kilobyte', 'Megabyte'],
    correct: 0,
  },
  {
    id: 4,
    text: 'Which of the following is NOT an input device?',
    options: ['Keyboard', 'Monitor', 'Mouse', 'Scanner'],
    correct: 1,
  },
  {
    id: 5,
    text: "Which language is directly understood by the computer's CPU?",
    options: ['Python', 'Machine Language', 'C++', 'Java'],
    correct: 1,
  },
  {
    id: 6,
    text: 'Which of these is a volatile memory?',
    options: ['Hard Drive', 'ROM', 'RAM', 'DVD'],
    correct: 2,
  },
  {
    id: 7,
    text: 'What does HTML stand for?',
    options: [
      'Hyper Text Markup Language',
      'High Tech Machine Language',
      'Home Tool Markup Language',
      'Hyperlinking Text Module Language',
    ],
    correct: 0,
  },
  {
    id: 8,
    text: 'Which HTML tag is used to create an ordered list?',
    options: ['<ul>', '<li>', '<ol>', '<br>'],
    correct: 2,
  },
  {
    id: 9,
    text: 'Which company developed the first microprocessor?',
    options: ['Microsoft', 'IBM', 'Intel', 'AMD'],
    correct: 2,
  },
  {
    id: 10,
    text: 'What is the primary purpose of an operating system?',
    options: [
      'Create documents',
      'Manage hardware and software resources',
      'Browse the internet',
      'Play games',
    ],
    correct: 1,
  },
  {
    id: 11,
    text: 'Which generation of computers used transistors?',
    options: ['First', 'Second', 'Third', 'Fourth'],
    correct: 1,
  },
  {
    id: 12,
    text: 'Which of the following is an example of system software?',
    options: [
      'Microsoft Word',
      'Google Chrome',
      'Windows Operating System',
      'Photoshop',
    ],
    correct: 2,
  },
  {
    id: 13,
    text: 'Which device is used to connect a computer to a network?',
    options: ['Printer', 'Router', 'Monitor', 'Scanner'],
    correct: 1,
  },
  {
    id: 14,
    text: 'What is the full form of CPU?',
    options: [
      'Central Processing Unit',
      'Central Program Unit',
      'Computer Processing Unit',
      'Central Power Unit',
    ],
    correct: 0,
  },
  {
    id: 15,
    text: 'Which of the following is an output device?',
    options: ['Microphone', 'Keyboard', 'Monitor', 'Joystick'],
    correct: 2,
  },
  {
    id: 16,
    text: 'Which computer memory is used for temporary data storage?',
    options: ['RAM', 'ROM', 'Hard Disk', 'CD-ROM'],
    correct: 0,
  },
  {
    id: 17,
    text: 'What is the term for physical parts of a computer?',
    options: ['Hardware', 'Software', 'Firmware', 'Malware'],
    correct: 0,
  },
  {
    id: 18,
    text: 'Which programming language is primarily used for web development?',
    options: ['C++', 'JavaScript', 'Python', 'Assembly'],
    correct: 1,
  },
  {
    id: 19,
    text: 'Which device is used to store large amounts of data permanently?',
    options: ['RAM', 'Cache', 'Hard Drive', 'CD-ROM'],
    correct: 2,
  },
  {
    id: 20,
    text: 'What is the main function of a compiler?',
    options: [
      'Execute code',
      'Translate code from high-level to machine language',
      'Debug code',
      'Optimize system performance',
    ],
    correct: 1,
  },
  {
    id: 21,
    text: 'Which company created the World Wide Web?',
    options: ['IBM', 'Microsoft', 'CERN', 'Google'],
    correct: 2,
  },
  {
    id: 22,
    text: 'Which symbol is used to denote an ID in CSS?',
    options: ['.', '#', '*', '@'],
    correct: 1,
  },
  {
    id: 23,
    text: 'Which tag is used to insert a line break in HTML?',
    options: ['<br>', '<lb>', '<break>', '<p>'],
    correct: 0,
  },
  {
    id: 24,
    text: 'Which software translates high-level language to machine code?',
    options: ['Assembler', 'Compiler', 'Interpreter', 'Debugger'],
    correct: 1,
  },
  {
    id: 25,
    text: 'Which of the following is an example of application software?',
    options: ['Operating System', 'Microsoft Excel', 'BIOS', 'Device Driver'],
    correct: 1,
  },
  {
    id: 26,
    text: 'What does GUI stand for?',
    options: [
      'Graphical User Interface',
      'General Unit Interface',
      'Graph Utility Interaction',
      'Global User Integration',
    ],
    correct: 0,
  },
  {
    id: 27,
    text: 'Which language is used to style web pages?',
    options: ['HTML', 'Python', 'CSS', 'Java'],
    correct: 2,
  },
  {
    id: 28,
    text: 'Which of the following is NOT an operating system?',
    options: ['Windows', 'Linux', 'Photoshop', 'MacOS'],
    correct: 2,
  },
  {
    id: 29,
    text: 'What is the primary purpose of cache memory?',
    options: [
      'Long-term storage',
      'Temporary data storage for quick access',
      'Store permanent files',
      'Networking',
    ],
    correct: 1,
  },
  {
    id: 30,
    text: 'Which HTML tag is used to create a table?',
    options: ['<div>', '<table>', '<form>', '<span>'],
    correct: 1,
  },
  {
    id: 31,
    text: 'What is the function of an ALU?',
    options: [
      'Store data',
      'Perform arithmetic and logical operations',
      'Manage memory',
      'Connect peripherals',
    ],
    correct: 1,
  },
  {
    id: 32,
    text: 'Which protocol is used for secure web communication?',
    options: ['HTTP', 'FTP', 'HTTPS', 'SMTP'],
    correct: 2,
  },
  {
    id: 33,
    text: 'Which of the following is a non-volatile memory?',
    options: ['RAM', 'Cache', 'ROM', 'Registers'],
    correct: 2,
  },
  {
    id: 34,
    text: 'What does URL stand for?',
    options: [
      'Uniform Resource Locator',
      'Universal Resource Link',
      'Unified Remote Link',
      'Universal Record Locator',
    ],
    correct: 0,
  },
  {
    id: 35,
    text: 'Which tag is used to create a list with bullets in HTML?',
    options: ['<ul>', '<ol>', '<li>', '<p>'],
    correct: 0,
  },
  {
    id: 36,
    text: 'Which device is responsible for connecting a computer to the internet?',
    options: ['Printer', 'Modem', 'RAM', 'CPU'],
    correct: 1,
  },
  {
    id: 37,
    text: 'What does IP stand for in IP address?',
    options: [
      'Internet Protocol',
      'Internal Program',
      'Interface Provider',
      'Interconnected Platform',
    ],
    correct: 0,
  },
  {
    id: 38,
    text: 'Which of the following is an example of secondary storage?',
    options: ['RAM', 'Cache', 'Hard Drive', 'Registers'],
    correct: 2,
  },
  {
    id: 39,
    text: 'Which HTML tag is used to insert an image?',
    options: ['<pic>', '<img>', '<image>', '<photo>'],
    correct: 1,
  },
  {
    id: 40,
    text: 'Which programming construct is used to make decisions in code?',
    options: ['Loop', 'Array', 'If-Else Statement', 'Function'],
    correct: 2,
  },
  {
    id: 41,
    text: 'Which of the following is NOT a web browser?',
    options: ['Chrome', 'Firefox', 'Windows Explorer', 'Edge'],
    correct: 2,
  },
  {
    id: 42,
    text: 'What is the purpose of a router?',
    options: [
      'Store data',
      'Perform calculations',
      'Connect networks',
      'Display graphics',
    ],
    correct: 2,
  },
  {
    id: 43,
    text: 'Which computer part is responsible for displaying images on the screen?',
    options: ['Motherboard', 'Graphics Card', 'Sound Card', 'Network Card'],
    correct: 1,
  },
  {
    id: 44,
    text: 'Which programming paradigm is based on the concept of objects?',
    options: [
      'Functional Programming',
      'Object-Oriented Programming',
      'Procedural Programming',
      'Logic Programming',
    ],
    correct: 1,
  },
  {
    id: 45,
    text: 'Which of the following is NOT a programming language?',
    options: ['Python', 'Java', 'HTML', 'C++'],
    correct: 2,
  },
  {
    id: 46,
    text: 'Which type of loop continues to execute as long as the condition is true?',
    options: ['for loop', 'while loop', 'do-while loop', 'foreach loop'],
    correct: 1,
  },
  {
    id: 47,
    text: 'Which data structure uses LIFO (Last In, First Out) principle?',
    options: ['Queue', 'Array', 'Stack', 'Linked List'],
    correct: 2,
  },
  {
    id: 48,
    text: 'Which JavaScript function is used to parse a string to an integer?',
    options: ['parseFloat()', 'Number()', 'int()', 'parseInt()'],
    correct: 3,
  },
  {
    id: 49,
    text: 'What does CSS stand for?',
    options: [
      'Cascading Style Sheets',
      'Computer Styling System',
      'Creative Style Syntax',
      'Custom Style Sheets',
    ],
    correct: 0,
  },
  {
    id: 50,
    text: 'Which HTML tag is used to create a hyperlink?',
    options: ['<link>', '<href>', '<a>', '<nav>'],
    correct: 2,
  },
  {
    id: 51,
    text: 'What is the primary purpose of JavaScript?',
    options: [
      'Designing web pages',
      'Adding interactivity to web pages',
      'Managing databases',
      'Creating server-side applications',
    ],
    correct: 1,
  },
  {
    id: 52,
    text: 'Which operator is used to concatenate strings in JavaScript?',
    options: ['+', '&', '||', '*'],
    correct: 0,
  },
  {
    id: 53,
    text: 'Which method is used to find the length of an array in JavaScript?',
    options: ['size()', 'length()', 'count()', 'index()'],
    correct: 1,
  },
  {
    id: 54,
    text: 'Which function is used to display a message box in JavaScript?',
    options: ['prompt()', 'console.log()', 'alert()', 'write()'],
    correct: 2,
  },
  {
    id: 55,
    text: 'Which tag is used to create a form in HTML?',
    options: ['<form>', '<input>', '<table>', '<button>'],
    correct: 0,
  },
  {
    id: 56,
    text: 'Which HTTP method is used to retrieve data from a server?',
    options: ['POST', 'PUT', 'GET', 'DELETE'],
    correct: 2,
  },
  {
    id: 57,
    text: 'Which protocol is used to send emails?',
    options: ['FTP', 'HTTP', 'SMTP', 'SSH'],
    correct: 2,
  },
  {
    id: 58,
    text: 'Which device is essential for wireless communication in a network?',
    options: ['Router', 'Switch', 'Hub', 'Firewall'],
    correct: 0,
  },
  {
    id: 59,
    text: 'Which HTML element is used to insert a JavaScript file?',
    options: ['<script>', '<link>', '<meta>', '<style>'],
    correct: 0,
  },
  {
    id: 60,
    text: 'Which property is used to change the background color in CSS?',
    options: ['color', 'bgcolor', 'background-color', 'font-color'],
    correct: 2,
  },
  {
    id: 61,
    text: 'Which of the following is a relational database management system (RDBMS)?',
    options: ['MySQL', 'Python', 'Visual Studio', 'Excel'],
    correct: 0,
  },
  {
    id: 62,
    text: 'Which network topology uses a single central cable to which all network devices are connected?',
    options: ['Star', 'Ring', 'Bus', 'Mesh'],
    correct: 2,
  },
  {
    id: 63,
    text: 'Which of the following is a web browser?',
    options: ['Linux', 'Firefox', 'Notepad++', 'Java'],
    correct: 1,
  },
  {
    id: 64,
    text: 'Which JavaScript keyword is used to declare a variable?',
    options: ['var', 'let', 'const', 'All of the above'],
    correct: 3,
  },
  {
    id: 65,
    text: 'Which function is used to execute a block of code repeatedly in JavaScript?',
    options: ['if', 'while', 'switch', 'try'],
    correct: 1,
  },
  {
    id: 66,
    text: 'Which symbol is used to access properties of an object in JavaScript?',
    options: ['.', ':', '#', '@'],
    correct: 0,
  },
  {
    id: 67,
    text: 'Which method is used to add a new element to the end of an array?',
    options: ['push()', 'pop()', 'shift()', 'unshift()'],
    correct: 0,
  },
  {
    id: 68,
    text: 'What does DOM stand for in web development?',
    options: [
      'Document Object Model',
      'Data Object Management',
      'Digital Online Memory',
      'Document Order Mapping',
    ],
    correct: 0,
  },
  {
    id: 69,
    text: 'Which tag is used to embed JavaScript code in an HTML document?',
    options: ['<js>', '<code>', '<script>', '<javascript>'],
    correct: 2,
  },
  {
    id: 70,
    text: 'Which operator is used to compare both value and type in JavaScript?',
    options: ['==', '===', '!=', '>='],
    correct: 1,
  },
  {
    id: 71,
    text: 'Which of the following is NOT a looping structure in JavaScript?',
    options: ['for', 'foreach', 'do-while', 'select'],
    correct: 3,
  },
  {
    id: 72,
    text: 'Which protocol is used for transferring files over the internet?',
    options: ['HTTP', 'SMTP', 'FTP', 'DNS'],
    correct: 2,
  },
  {
    id: 73,
    text: 'What does API stand for?',
    options: [
      'Application Programming Interface',
      'Automated Program Interaction',
      'Applied Protocol Integration',
      'Application Process Integration',
    ],
    correct: 0,
  },
  {
    id: 74,
    text: 'Which method is used to remove the last element from an array?',
    options: ['slice()', 'pop()', 'splice()', 'delete()'],
    correct: 1,
  },
  {
    id: 75,
    text: 'Which SQL command is used to retrieve data from a database?',
    options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'],
    correct: 2,
  },
  {
    id: 76,
    text: 'Which attribute is used to uniquely identify an HTML element?',
    options: ['class', 'name', 'id', 'type'],
    correct: 2,
  },
  {
    id: 77,
    text: 'Which method converts a JSON string into a JavaScript object?',
    options: [
      'JSON.stringify()',
      'JSON.parse()',
      'object.toString()',
      'parse.JSON()',
    ],
    correct: 1,
  },
  {
    id: 78,
    text: 'Which tag is used to create a drop-down list in HTML?',
    options: ['<select>', '<list>', '<dropdown>', '<option>'],
    correct: 0,
  },
  {
    id: 79,
    text: 'Which part of a computer executes instructions from software?',
    options: ['RAM', 'GPU', 'CPU', 'Hard Disk'],
    correct: 2,
  },
  {
    id: 80,
    text: 'Which HTML element is used to define important text?',
    options: ['<strong>', '<em>', '<mark>', '<b>'],
    correct: 0,
  },
  {
    id: 81,
    text: 'Which function is used to join two or more arrays in JavaScript?',
    options: ['concat()', 'merge()', 'join()', 'combine()'],
    correct: 0,
  },
  {
    id: 82,
    text: 'Which of the following represents a one-to-many relationship in databases?',
    options: ['Primary Key', 'Foreign Key', 'Unique Key', 'Index'],
    correct: 1,
  },
  {
    id: 83,
    text: 'Which device connects multiple computers in a local network?',
    options: ['Router', 'Switch', 'Firewall', 'Modem'],
    correct: 1,
  },
  {
    id: 84,
    text: 'Which of the following best describes a computer virus?',
    options: [
      'A hardware component',
      'A malicious program that replicates itself',
      'A type of software update',
      'An error in the operating system',
    ],
    correct: 1,
  },
  {
    id: 85,
    text: 'Which JavaScript method is used to manipulate strings by extracting a portion of it?',
    options: ['slice()', 'split()', 'push()', 'filter()'],
    correct: 0,
  },
  {
    id: 86,
    text: 'Which protocol is used to translate domain names into IP addresses?',
    options: ['SMTP', 'DNS', 'HTTP', 'FTP'],
    correct: 1,
  },
  {
    id: 87,
    text: 'Which HTML element is used to play video files?',
    options: ['<media>', '<video>', '<embed>', '<play>'],
    correct: 1,
  },
  {
    id: 88,
    text: 'Which type of cyber attack involves overwhelming a network or website with excessive traffic?',
    options: ['Phishing', 'DDoS', 'SQL Injection', 'Trojan'],
    correct: 1,
  },
  {
    id: 89,
    text: 'Which HTML element is used to display a progress bar?',
    options: ['<progress>', '<meter>', '<bar>', '<status>'],
    correct: 0,
  },
  {
    id: 90,
    text: 'Which JavaScript method is used to find the position of the first occurrence of a specified value in a string?',
    options: ['indexOf()', 'find()', 'search()', 'locate()'],
    correct: 0,
  },
  {
    id: 91,
    text: 'Which of the following is considered the most secure method of user authentication?',
    options: [
      'Username and Password',
      'Captcha',
      'Biometric Authentication',
      'Security Questions',
    ],
    correct: 2,
  },
  {
    id: 92,
    text: 'Which of the following is NOT an example of an operating system?',
    options: ['Linux', 'Windows', 'Android', 'MySQL'],
    correct: 3,
  },
  {
    id: 93,
    text: 'Which JavaScript function is used to delay the execution of code?',
    options: ['setInterval()', 'setTimeout()', 'wait()', 'pause()'],
    correct: 1,
  },
  {
    id: 94,
    text: 'Which HTML element is used to create a clickable button?',
    options: ['<button>', '<a>', '<input>', '<click>'],
    correct: 0,
  },
  {
    id: 95,
    text: 'Which CSS property is used to make text bold?',
    options: ['font-weight', 'text-style', 'font-bold', 'font-color'],
    correct: 0,
  },
  {
    id: 96,
    text: 'Which JavaScript function rounds a number to the nearest integer?',
    options: ['Math.floor()', 'Math.ceil()', 'Math.round()', 'Math.abs()'],
    correct: 2,
  },
  {
    id: 97,
    text: 'Which of the following is used to protect a computer from unauthorized access over the internet?',
    options: ['Router', 'Firewall', 'Switch', 'Proxy Server'],
    correct: 1,
  },
  {
    id: 98,
    text: 'Which tag is used to define an interactive form in HTML?',
    options: ['<div>', '<form>', '<section>', '<table>'],
    correct: 1,
  },
  {
    id: 99,
    text: 'Which of the following is NOT an example of malware?',
    options: ['Trojan', 'Firewall', 'Spyware', 'Ransomware'],
    correct: 1,
  },
  {
    id: 100,
    text: 'Which JavaScript method can be used to convert an array into a string?',
    options: ['join()', 'concat()', 'split()', 'toString()'],
    correct: 0,
  },
  {
    id: 101,
    text: 'Which of the following is a key component of network security?',
    options: ['Switch', 'Router', 'Encryption', 'Monitor'],
    correct: 2,
  },
  {
    id: 102,
    text: 'Which of the following tags is used to create an ordered list in HTML?',
    options: ['<ul>', '<li>', '<ol>', '<list>'],
    correct: 2,
  },
  {
    id: 103,
    text: 'Which CSS property is used to add spacing between the content and the border of an element?',
    options: ['margin', 'padding', 'border-spacing', 'line-height'],
    correct: 1,
  },
];
