export const cs408 = [
    {
      id: 1,
      text: 'What is the primary focus of User-Centered Design (UCD)?',
      options: [
        'Technology and its capabilities',
        'Designers’ preferences',
        'Real users and their goals',
        'Cost reduction',
      ],
      correct: 3,
    },
    {
      id: 2,
      text: 'Which principle is NOT part of Gould and Lewis’s user-centered design approach?',
      options: [
        'Early focus on users and tasks',
        'Empirical measurement',
        'Iterative design',
        'Design driven by business goals only',
      ],
      correct: 4,
    },
    {
      id: 3,
      text: 'What type of research helps understand user behavior in detail, answering questions like "what" and "why"?',
      options: [
        'Quantitative research',
        'Qualitative research',
        'Statistical analysis',
        'Focus groups only',
      ],
      correct: 2,
    },
    {
      id: 4,
      text: 'Which technique is typically used in ethnographic research?',
      options: [
        'Surveys',
        'Contextual interviews',
        'A/B testing',
        'Software testing',
      ],
      correct: 2,
    },
    {
      id: 5,
      text: 'What is the primary goal during early-phase ethnographic interviews?',
      options: [
        'Clarify patterns of use',
        'Ask closed-ended questions',
        'Exploration and domain knowledge gathering',
        'Focus on system functionalities',
      ],
      correct: 3,
    },
    {
      id: 6,
      text: 'In user research, what does "persona" represent?',
      options: [
        'A fictional character unrelated to the design',
        'A real individual used directly in the design',
        'A composite archetype based on user data',
        'A design tool to test system performance',
      ],
      correct: 3,
    },
    {
      id: 7,
      text: 'What does a goal-oriented question in ethnographic interviews typically address?',
      options: [
        'Daily routines and processes',
        'User aspirations and desired outcomes',
        'Software bugs and errors',
        'Marketing demographics',
      ],
      correct: 2,
    },
    {
      id: 8,
      text: 'Why is iterative design important in user-centered development?',
      options: [
        'It ensures all initial designs are correct',
        'It reduces the number of interviews needed',
        'It allows continuous improvement based on feedback',
        'It focuses on developers’ preferences over users',
      ],
      correct: 3,
    },
    {
      id: 9,
      text: 'Which aspect is emphasized in personas during the modeling phase?',
      options: [
        'Technical specifications',
        'Observed behaviors and motivations',
        'System configurations',
        'Coding patterns',
      ],
      correct: 2,
    },
    {
      id: 10,
      text: 'Which of the following is a phase in ethnographic interviews?',
      options: [
        'System testing',
        'Prototyping',
        'Goal-oriented questioning',
        'Product launch',
      ],
      correct: 3,
    },
    {
      id: 11,
      text: 'What is a narrative used for in the requirements phase of HCI design?',
      options: [
        'To explain software architecture',
        'To describe user interactions and envision solutions',
        'To define pricing models',
        'To create system documentation',
      ],
      correct: 2,
    },
    {
      id: 12,
      text: 'What is the main benefit of using scenarios in design?',
      options: [
        'Increases cost of development',
        'Focuses on system speed optimization',
        'Allows articulation of design possibilities',
        'Eliminates need for user testing',
      ],
      correct: 3,
    },
    {
      id: 13,
      text: 'Which of the following is NOT a type of goal in persona construction?',
      options: [
        'Experience goals',
        'End goals',
        'Life goals',
        'Marketing goals',
      ],
      correct: 4,
    },
    {
      id: 14,
      text: 'Which user model is considered the most effective for interaction designers?',
      options: [
        'Task models',
        'Personas',
        'Mathematical models',
        'Demographic models',
      ],
      correct: 2,
    },
    {
      id: 15,
      text: 'Which phase involves confirming patterns of use and user roles?',
      options: [
        'Early-phase',
        'Mid-phase',
        'Late-phase',
        'Testing-phase',
      ],
      correct: 3,
    },
    {
      id: 16,
      text: 'How many interviews are typically conducted per persona variable?',
      options: [
        '1-2',
        '4-6',
        '10-12',
        '15-20',
      ],
      correct: 2,
    },
    {
      id: 17,
      text: 'Which of the following is a primary characteristic of qualitative research?',
      options: [
        'Focuses on numerical data',
        'Provides insights into user behaviors and motivations',
        'Conducted in lab environments only',
        'Excludes open-ended questions',
      ],
      correct: 2,
    },
    {
      id: 18,
      text: 'What is a key outcome of ethnographic research?',
      options: [
        'Coding system errors',
        'Identifying user workflows and pain points',
        'Optimizing hardware components',
        'Generating system requirements',
      ],
      correct: 2,
    },
    {
      id: 19,
      text: 'Which method combines both interviews and real-time observation?',
      options: [
        'Focus groups',
        'Surveys',
        'User observation',
        'Product testing',
      ],
      correct: 3,
    },
    {
      id: 20,
      text: 'What role do personas play in the design process?',
      options: [
        'They reduce the need for user interviews',
        'They act as substitutes for testing',
        'They represent user goals and behaviors',
        'They define hardware specifications',
      ],
      correct: 3,
    },
    {
      id: 21,
      text: 'What is the first step in defining an interaction framework?',
      options: [
        'Sketching the interaction framework',
        'Defining form factor and input methods',
        'Determining functional groups and hierarchy',
        'Constructing key path scenarios',
      ],
      correct: 2,
    },
    {
      id: 22,
      text: 'Which element is crucial during the prototyping phase?',
      options: [
        'Hardware specifications',
        'Design sketches and scenarios',
        'Marketing goals',
        'Sales targets',
      ],
      correct: 2,
    },
    {
      id: 23,
      text: 'Which of the following represents a design imperative?',
      options: [
        'Visual aesthetics',
        'Consistency in icons',
        'Designing for elegance and efficiency',
        'Limited user interaction',
      ],
      correct: 3,
    },
    {
      id: 24,
      text: 'What does "posture" represent in software design?',
      options: [
        'The aesthetic appeal of software',
        'The behavior and manner in which software interacts with users',
        'The coding language used for development',
        'The pricing model for the software',
      ],
      correct: 2,
    },
    {
      id: 25,
      text: 'Which of the following is a sovereign attribute of software posture?',
      options: [
        'Minimal screen usage',
        'Bold, full-screen presence',
        'Hidden background processes',
        'Lightweight applications',
      ],
      correct: 2,
    },
    {
      id: 26,
      text: 'Which of the following best describes transient software posture?',
      options: [
        'Continuously visible and dominant',
        'Hidden but active in the background',
        'Appears temporarily to support tasks',
        'Monitors user activity constantly',
      ],
      correct: 3,
    },
    {
      id: 27,
      text: 'Which design element is critical for reducing user workload?',
      options: [
        'Logical work',
        'Physical work',
        'Aesthetic work',
        'Perceptual work',
      ],
      correct: 4,
    },
    {
      id: 28,
      text: 'Which attribute is essential in creating interaction design patterns?',
      options: [
        'Uniqueness and complexity',
        'Replication of existing designs',
        'Generalizable solutions to design problems',
        'Marketing-driven designs',
      ],
      correct: 3,
    },
    {
      id: 29,
      text: 'Why are personas critical in design synthesis?',
      options: [
        'They improve technical documentation',
        'They represent user goals and behaviors',
        'They enhance software speed',
        'They limit design possibilities',
      ],
      correct: 2,
    },
    {
      id: 30,
      text: 'What is the purpose of orchestration in software behavior?',
      options: [
        'To focus on user interface color schemes',
        'To manage system updates silently',
        'To coordinate flow and interaction of features',
        'To promote software sales',
      ],
      correct: 3,
    },
    {
      id: 31,
      text: 'Which software posture best describes auxiliary programs?',
      options: [
        'Transient and hidden',
        'Supporting but consistently present',
        'Bold and full-screen',
        'Inactive until prompted',
      ],
      correct: 2,
    },
    {
      id: 32,
      text: 'What influences whether a website adopts sovereign or transient attributes?',
      options: [
        'User return frequency and content updates',
        'Marketing strategies',
        'Graphics and animations',
        'Choice of programming language',
      ],
      correct: 1,
    },
    {
      id: 33,
      text: 'What is an example of transient software on a desktop?',
      options: [
        'Operating system settings',
        'Task manager',
        'Media player',
        'Web browser',
      ],
      correct: 3,
    },
    {
      id: 34,
      text: 'Which phase ensures flow and transparency in web design?',
      options: [
        'Initial prototyping',
        'Orchestration phase',
        'Evaluation phase',
        'Interaction synthesis',
      ],
      correct: 2,
    },
    {
      id: 35,
      text: 'What is the primary goal of design synthesis?',
      options: [
        'To create hardware prototypes',
        'To evaluate competitor designs',
        'To integrate interaction design principles and patterns',
        'To write technical documentation',
      ],
      correct: 3,
    },
    {
      id: 36,
      text: 'Which interaction design principle minimizes logical work for users?',
      options: [
        'Reducing screen size',
        'Increasing font size',
        'Simplifying information processing',
        'Using vibrant colors',
      ],
      correct: 3,
    },
    {
      id: 37,
      text: 'Which element reflects perceptual work in design?',
      options: [
        'Understanding system architecture',
        'Navigating visual layouts and colors',
        'Adjusting software code',
        'Analyzing backend databases',
      ],
      correct: 2,
    },
    {
      id: 38,
      text: 'What is a key goal in designing postures for web applications?',
      options: [
        'Minimize user involvement',
        'Create sovereign experiences for all users',
        'Balance information density with ease of use',
        'Focus on vibrant animations',
      ],
      correct: 3,
    },
    {
      id: 39,
      text: 'Which feature is emphasized in sovereign web design?',
      options: [
        'Minimal screen space usage',
        'Partial-screen displays',
        'Full-screen display and detailed information',
        'Background operation only',
      ],
      correct: 3,
    },
    {
      id: 40,
      text: 'What is the primary focus during the refinement phase of design?',
      options: [
        'User feedback and interface coherence',
        'Market expansion',
        'Cost reduction',
        'Hardware performance',
      ],
      correct: 1,
    },
    {
      id: 41,
      text: 'What is the primary goal of eliminating excise in software design?',
      options: [
        'To reduce unnecessary work for the user',
        'To increase the complexity of software',
        'To enhance software aesthetics only',
        'To add more features',
      ],
      correct: 1,
    },
    {
      id: 42,
      text: 'Which of the following is an example of excise in software interaction?',
      options: [
        'Clicking "Save" to retain document changes',
        'Entering repeated login credentials frequently',
        'Typing a new document',
        'Viewing notifications',
      ],
      correct: 2,
    },
    {
      id: 43,
      text: 'What technique is primarily used to reduce excise in software?',
      options: [
        'Adding more user prompts',
        'Minimizing redundant tasks',
        'Increasing UI complexity',
        'Focusing on developer convenience',
      ],
      correct: 2,
    },
    {
      id: 44,
      text: 'In evaluation, what does "validity" refer to?',
      options: [
        'Whether the technique measures what it claims to measure',
        'The speed of the evaluation process',
        'The number of participants involved',
        'The use of automated tools',
      ],
      correct: 1,
    },
    {
      id: 45,
      text: 'Which type of evaluation has high ecological validity?',
      options: [
        'Laboratory experiments',
        'Ethnographic studies',
        'Usability testing in controlled environments',
        'Heuristic evaluations',
      ],
      correct: 2,
    },
    {
      id: 46,
      text: 'What is the primary goal of the DECIDE evaluation framework?',
      options: [
        'To enhance marketing strategies',
        'To guide the evaluation process systematically',
        'To increase project budgets',
        'To replace traditional design approaches',
      ],
      correct: 2,
    },
    {
      id: 47,
      text: 'In the DECIDE framework, what does the "C" stand for?',
      options: [
        'Choose the evaluation paradigm and techniques',
        'Calculate performance metrics',
        'Create personas',
        'Check for software bugs',
      ],
      correct: 1,
    },
    {
      id: 48,
      text: 'Which method involves stepping through tasks to identify design issues?',
      options: [
        'User testing',
        'Software inspection',
        'Heuristic evaluation',
        'Task modeling',
      ],
      correct: 3,
    },
    {
      id: 49,
      text: 'What is the primary goal of formative evaluation?',
      options: [
        'To assess the final product',
        'To improve design during development',
        'To market the product',
        'To conduct sales analysis',
      ],
      correct: 2,
    },
    {
      id: 50,
      text: 'What term describes the extent to which evaluation findings can be generalized?',
      options: [
        'Scope',
        'Bias',
        'Ecological validity',
        'Reliability',
      ],
      correct: 1,
    },
    {
      id: 51,
      text: 'Which factor contributes to bias in usability evaluation?',
      options: [
        'Randomized user selection',
        'Evaluator subjectivity',
        'Objective task criteria',
        'Automated tools',
      ],
      correct: 2,
    },
    {
      id: 52,
      text: 'Which evaluation technique is cost-effective and quick?',
      options: [
        'Field studies',
        'Heuristic evaluation',
        'Longitudinal studies',
        'Focus groups',
      ],
      correct: 2,
    },
    {
      id: 53,
      text: 'What is the main focus of summative evaluation?',
      options: [
        'Improving user personas',
        'Final product assessment',
        'Brainstorming design ideas',
        'Creating wireframes',
      ],
      correct: 2,
    },
    {
      id: 54,
      text: 'In evaluation, what does "bias" most commonly affect?',
      options: [
        'Data accuracy',
        'Software aesthetics',
        'System performance',
        'Budget allocation',
      ],
      correct: 1,
    },
    {
      id: 55,
      text: 'Which factor improves the reliability of usability testing?',
      options: [
        'Involving only experts',
        'Testing in natural environments',
        'Standardized task scenarios',
        'Reducing the number of participants',
      ],
      correct: 3,
    },
    {
      id: 56,
      text: 'Which part of the DECIDE framework addresses ethical concerns?',
      options: [
        'Evaluate and present data',
        'Identify practical issues',
        'Explore evaluation questions',
        'Decide how to deal with ethical issues',
      ],
      correct: 4,
    },
    {
      id: 57,
      text: 'What is the focus of "orchestration" in interaction design?',
      options: [
        'Managing user flows and transitions',
        'Adding new features',
        'Reducing software costs',
        'Enhancing hardware integration',
      ],
      correct: 1,
    },
    {
      id: 58,
      text: 'Which element is evaluated to ensure consistency in UI design?',
      options: [
        'Color schemes',
        'User data',
        'Underlying software code',
        'Network latency',
      ],
      correct: 1,
    },
    {
      id: 59,
      text: 'What is the main objective of user-centered evaluation?',
      options: [
        'To validate user needs and usability',
        'To increase software speed',
        'To reduce development costs',
        'To enhance developer experience',
      ],
      correct: 1,
    },
    {
      id: 60,
      text: 'Which factor is most critical for the success of usability testing?',
      options: [
        'High participant numbers',
        'Clear evaluation goals',
        'Complex evaluation tools',
        'Extensive marketing research',
      ],
      correct: 2,
    },

    {
      id: 61,
      text: 'What is the primary goal of web navigation design?',
      options: [
        'To showcase advanced graphics',
        'To minimize development costs',
        'To ensure users can find what they need quickly',
        'To highlight advertisements',
      ],
      correct: 3,
    },
    {
      id: 62,
      text: 'Which component is essential for effective web navigation?',
      options: [
        'Decorative images',
        'Breadcrumb trails',
        'Pop-up ads',
        'Complex animations',
      ],
      correct: 2,
    },
    {
      id: 63,
      text: 'What is the key principle behind the "trunk test" for web design?',
      options: [
        'Ensuring consistent color schemes',
        'Determining usability by asking key navigation questions',
        'Evaluating backend performance',
        'Testing server capacity',
      ],
      correct: 2,
    },
    {
      id: 64,
      text: 'Which of the following is a critical question in the trunk test?',
      options: [
        'What is the color scheme of the site?',
        'Where am I in the site hierarchy?',
        'How fast does the site load?',
        'What programming language is used?',
      ],
      correct: 2,
    },
    {
      id: 65,
      text: 'Why are highlighted tabs important in web navigation?',
      options: [
        'To attract users to promotions',
        'To indicate the current location of the user',
        'To display advertisements',
        'To limit navigation options',
      ],
      correct: 2,
    },
    {
      id: 66,
      text: 'Which of the following should NOT be included on a homepage?',
      options: [
        'Clear navigation links',
        'Site ID and page name',
        'Version numbers',
        'Search functionality',
      ],
      correct: 3,
    },
    {
      id: 67,
      text: 'What is the goal of heuristic evaluation in usability testing?',
      options: [
        'To develop advanced graphics',
        'To identify usability issues using expert reviews',
        'To optimize server load times',
        'To assess software coding quality',
      ],
      correct: 2,
    },
    {
      id: 68,
      text: 'Which usability principle is emphasized during web navigation design?',
      options: [
        'Aesthetic design',
        'Consistency and simplicity',
        'Frequent pop-ups',
        'Complex layouts',
      ],
      correct: 2,
    },
    {
      id: 69,
      text: 'What should a well-designed "You are here" indicator provide?',
      options: [
        'A link to external sites',
        'A visual cue showing the user’s location in the site hierarchy',
        'A large advertisement banner',
        'A form for user feedback',
      ],
      correct: 2,
    },
    {
      id: 70,
      text: 'Which method can improve clarity in breadcrumb navigation?',
      options: [
        'Using bold and color contrasts',
        'Embedding videos',
        'Adding multiple advertisements',
        'Reducing navigation options',
      ],
      correct: 1,
    },
    {
      id: 71,
      text: 'Which aspect of usability does evaluation primarily focus on?',
      options: [
        'Marketing strategies',
        'System performance',
        'User experience and satisfaction',
        'Financial analysis',
      ],
      correct: 3,
    },
    {
      id: 72,
      text: 'What type of evaluation occurs during the development process to improve design?',
      options: [
        'Summative evaluation',
        'Formative evaluation',
        'Financial evaluation',
        'Performance testing',
      ],
      correct: 2,
    },
    {
      id: 73,
      text: 'What is the purpose of summative evaluation?',
      options: [
        'To refine product design during development',
        'To assess the success of a finished product',
        'To develop new product features',
        'To conduct market research',
      ],
      correct: 2,
    },
    {
      id: 74,
      text: 'Which of the following improves web usability most effectively?',
      options: [
        'Flashy animations',
        'Consistent layout and clear navigation',
        'Frequent advertisements',
        'Complex data forms',
      ],
      correct: 2,
    },
    {
      id: 75,
      text: 'Why is user feedback crucial during evaluation?',
      options: [
        'To reduce production costs',
        'To identify usability issues',
        'To increase software complexity',
        'To develop new programming languages',
      ],
      correct: 2,
    },
    {
      id: 76,
      text: 'Which is an example of direct observation in evaluation?',
      options: [
        'Surveys',
        'Watching users interact with a product',
        'Analyzing web traffic',
        'Reading product reviews',
      ],
      correct: 2,
    },
    {
      id: 77,
      text: 'What is the main focus of heuristic evaluations?',
      options: [
        'To evaluate visual design',
        'To identify usability issues based on guidelines',
        'To develop animations',
        'To test server performance',
      ],
      correct: 2,
    },
    {
      id: 78,
      text: 'Which phase of evaluation addresses ethical concerns?',
      options: [
        'Formulating research questions',
        'Selecting participants',
        'Ensuring data privacy and participant consent',
        'Testing system performance',
      ],
      correct: 3,
    },
    {
      id: 79,
      text: 'What is a common challenge in web usability testing?',
      options: [
        'Accessing high-speed internet',
        'Finding participants who fit the target audience',
        'Developing attractive advertisements',
        'Embedding video content',
      ],
      correct: 2,
    },
    {
      id: 80,
      text: 'What aspect of web navigation can reduce user frustration?',
      options: [
        'Clear page titles and headings',
        'Embedding complex graphics',
        'Using pop-up windows',
        'Hiding site IDs',
      ],
      correct: 1,
    },

    {
      id: 81,
      text: 'What is the primary purpose of the undo function in software design?',
      options: [
        'To improve visual aesthetics',
        'To allow users to reverse actions and correct mistakes',
        'To enhance system performance',
        'To restart the software',
      ],
      correct: 2,
    },
    {
      id: 82,
      text: 'Which of the following best describes single-level undo?',
      options: [
        'It allows users to undo multiple actions',
        'It undoes the last action only',
        'It prevents undo functionality',
        'It resets the software to factory settings',
      ],
      correct: 2,
    },
    {
      id: 83,
      text: 'Which undo model is preferred for complex user tasks?',
      options: [
        'Linear undo',
        'Hierarchical undo',
        'Single-step undo',
        'No undo',
      ],
      correct: 2,
    },
    {
      id: 84,
      text: 'What is a significant advantage of multiple-level undo?',
      options: [
        'It consumes less memory',
        'Users can correct several mistakes in sequence',
        'It simplifies code structure',
        'It eliminates the need for user confirmation',
      ],
      correct: 2,
    },
    {
      id: 85,
      text: 'What does the term "considerate software" refer to?',
      options: [
        'Software that operates without errors',
        'Software that anticipates user needs and minimizes disruption',
        'Software that focuses solely on design aesthetics',
        'Software with no user input required',
      ],
      correct: 2,
    },
    {
      id: 86,
      text: 'How can software be made "considerate"?',
      options: [
        'By limiting user choices',
        'By providing helpful feedback and remembering user preferences',
        'By forcing frequent updates',
        'By restricting system access',
      ],
      correct: 2,
    },
    {
      id: 87,
      text: 'What principle underlies the unified document management approach?',
      options: [
        'Documents are treated as single entities, not multiple copies',
        'Documents are duplicated for each task',
        'Users manually save files frequently',
        'Files are managed independently from user input',
      ],
      correct: 1,
    },
    {
      id: 88,
      text: 'Which of the following improves the look and feel of software interfaces?',
      options: [
        'Adding more icons',
        'Using principles of visual interface design',
        'Increasing text size randomly',
        'Reducing functionality',
      ],
      correct: 2,
    },
    {
      id: 89,
      text: 'What does "visual hierarchy" in interface design achieve?',
      options: [
        'It organizes elements by importance and guides user attention',
        'It hides important features',
        'It limits user interaction',
        'It prevents customization',
      ],
      correct: 1,
    },
    {
      id: 90,
      text: 'Which element is crucial for providing visual structure in interface design?',
      options: [
        'Random color selection',
        'Grid alignment of elements',
        'Excessive white space',
        'Invisible buttons',
      ],
      correct: 2,
    },
    {
      id: 91,
      text: 'What is the purpose of aligning labels and controls in interface design?',
      options: [
        'To increase aesthetic appeal',
        'To improve user readability and usability',
        'To reduce design time',
        'To restrict navigation',
      ],
      correct: 2,
    },
    {
      id: 92,
      text: 'Why is layering important in visual interface design?',
      options: [
        'To create a sense of depth and organization',
        'To make the interface more complex',
        'To add random colors',
        'To reduce screen space',
      ],
      correct: 1,
    },
    {
      id: 93,
      text: 'Which design principle enhances software usability the most?',
      options: [
        'Providing consistent feedback and intuitive interfaces',
        'Adding more animations',
        'Increasing data entry forms',
        'Focusing solely on marketing goals',
      ],
      correct: 1,
    },
    {
      id: 94,
      text: 'What is the role of feedback in user interface design?',
      options: [
        'To confirm user actions and provide guidance',
        'To prevent users from making choices',
        'To confuse users with excessive information',
        'To hide errors from users',
      ],
      correct: 1,
    },
    {
      id: 95,
      text: 'Which of the following represents a key aspect of visual structure in interfaces?',
      options: [
        'Random placement of elements',
        'Proper grouping and alignment of elements',
        'Complex menus without guidance',
        'Hidden navigational tools',
      ],
      correct: 2,
    },
    {
      id: 96,
      text: 'What is the goal of providing visual flow in interface design?',
      options: [
        'To slow down user interaction',
        'To guide users smoothly through tasks',
        'To add decorative elements',
        'To reduce usability',
      ],
      correct: 2,
    },
    {
      id: 97,
      text: 'Why is consistent use of color important in visual design?',
      options: [
        'To randomly highlight sections',
        'To create visual coherence and improve usability',
        'To distract users',
        'To reduce interface quality',
      ],
      correct: 2,
    },
    {
      id: 98,
      text: 'Which of the following enhances software memory functions?',
      options: [
        'Storing user preferences and previous interactions',
        'Deleting old data frequently',
        'Reducing system storage',
        'Preventing data collection',
      ],
      correct: 1,
    },
    {
      id: 99,
      text: 'How does "smart software" improve user experience?',
      options: [
        'By predicting user needs and automating tasks',
        'By restricting user input',
        'By ignoring user data',
        'By focusing on complex coding structures',
      ],
      correct: 1,
    },
    {
      id: 100,
      text: 'What principle should guide the placement of elements in an interface?',
      options: [
        'Random positioning',
        'Grid-based alignment',
        'Using multiple overlapping layers',
        'Reducing white space',
      ],
      correct: 2,
    },

    {
      id: 101,
      text: 'What is the primary goal of observing users during product development?',
      options: [
        'To test the software’s performance',
        'To understand user needs and context of use',
        'To improve marketing strategies',
        'To increase system speed',
      ],
      correct: 2,
    },
    {
      id: 102,
      text: 'Which of the following methods is used in controlled environments for user observation?',
      options: [
        'Field studies',
        'Direct observation with video recording',
        'Surveys',
        'Focus groups',
      ],
      correct: 2,
    },
    {
      id: 103,
      text: 'Which observation technique focuses on studying users in their natural environment?',
      options: [
        'Laboratory studies',
        'Usability testing',
        'Ethnography',
        'A/B testing',
      ],
      correct: 3,
    },
    {
      id: 104,
      text: 'When is user observation most beneficial in the product development cycle?',
      options: [
        'After product launch',
        'During late-stage development',
        'At any time during development',
        'Only during prototyping',
      ],
      correct: 3,
    },
    {
      id: 105,
      text: 'Which data collection tool is commonly used for field studies?',
      options: [
        'Video recording and note-taking',
        'Server logs',
        'A/B testing reports',
        'Marketing analytics',
      ],
      correct: 1,
    },
    {
      id: 106,
      text: 'What type of interviews allows the interviewer to deviate from preset questions?',
      options: [
        'Structured interviews',
        'Unstructured interviews',
        'Focus groups',
        'Surveys',
      ],
      correct: 2,
    },
    {
      id: 107,
      text: 'Which interview type is best suited for gaining first impressions on new designs?',
      options: [
        'Open-ended interviews',
        'Closed surveys',
        'Heuristic evaluations',
        'Performance testing',
      ],
      correct: 1,
    },
    {
      id: 108,
      text: 'What is the main advantage of semi-structured interviews?',
      options: [
        'They follow a rigid script',
        'They blend structure with flexibility',
        'They avoid all predefined questions',
        'They focus solely on group dynamics',
      ],
      correct: 2,
    },
    {
      id: 109,
      text: 'What type of evaluation involves asking experts to review an interface?',
      options: [
        'Heuristic evaluation',
        'A/B testing',
        'Ethnographic observation',
        'Surveys',
      ],
      correct: 1,
    },
    {
      id: 110,
      text: 'Which feedback mechanism helps eliminate the need for disruptive error messages?',
      options: [
        'Modal dialogs',
        'Rich visual modeless feedback',
        'System alerts',
        'Surveys',
      ],
      correct: 2,
    },
    {
      id: 111,
      text: 'What is a common characteristic of rich modeless feedback?',
      options: [
        'It requires user input to proceed',
        'It is always visible without interruption',
        'It halts the user’s task',
        'It blocks all further actions',
      ],
      correct: 2,
    },
    {
      id: 112,
      text: 'Which type of communication focuses on notifying users without stopping workflow?',
      options: [
        'Dialog boxes',
        'Pop-up alerts',
        'Modeless feedback',
        'Confirmation messages',
      ],
      correct: 3,
    },
    {
      id: 113,
      text: 'What is the key disadvantage of error dialog boxes in user interfaces?',
      options: [
        'They provide immediate feedback',
        'They disrupt user workflow unnecessarily',
        'They help clarify user mistakes',
        'They offer valuable insights',
      ],
      correct: 2,
    },
    {
      id: 114,
      text: 'What alternative to error dialogs allows for smoother user interaction?',
      options: [
        'Modal pop-ups',
        'Rich modeless feedback',
        'Static labels',
        'Command-line inputs',
      ],
      correct: 2,
    },
    {
      id: 115,
      text: 'In which scenario is associative information retrieval most useful?',
      options: [
        'Finding files based on storage location',
        'Searching for documents by content attributes',
        'Retrieving items by their file name only',
        'Sorting files by creation date',
      ],
      correct: 2,
    },
    {
      id: 116,
      text: 'Which system retrieves documents based on attributes rather than their location?',
      options: [
        'Indexed storage system',
        'Associative retrieval system',
        'Positional retrieval system',
        'Hierarchical storage system',
      ],
      correct: 2,
    },
    {
      id: 117,
      text: 'Which feedback type signals user errors through sound or visual cues?',
      options: [
        'Silent alerts',
        'Negative audible feedback',
        'Positive modal feedback',
        'System notifications',
      ],
      correct: 2,
    },
    {
      id: 118,
      text: 'Why is attribute-based retrieval superior to positional retrieval?',
      options: [
        'It organizes files by size',
        'It reduces the need for folders',
        'It allows users to find documents based on content',
        'It prioritizes file name over content',
      ],
      correct: 3,
    },
    {
      id: 119,
      text: 'What is a key benefit of using breadcrumbs in information retrieval systems?',
      options: [
        'They improve aesthetics',
        'They show user location in site hierarchy',
        'They increase load time',
        'They create random navigation paths',
      ],
      correct: 2,
    },
    {
      id: 120,
      text: 'Which retrieval method depends on the user knowing the exact location of a file?',
      options: [
        'Associative retrieval',
        'Hierarchical retrieval',
        'Positional retrieval',
        'Indexed retrieval',
      ],
      correct: 3,
    },
    {
      id: 121,
      text: 'What is the primary goal of ubiquitous computing?',
      options: [
        'To separate computing devices from the environment',
        'To integrate computation into the environment seamlessly',
        'To focus on desktop computing only',
        'To eliminate mobile devices',
      ],
      correct: 2,
    },
    {
      id: 122,
      text: 'Which term describes embedding computation into everyday objects?',
      options: [
        'Augmented reality',
        'Virtual reality',
        'Ubiquitous computing',
        'Cloud computing',
      ],
      correct: 3,
    },
    {
      id: 123,
      text: 'Who is considered the pioneer of ubiquitous computing?',
      options: [
        'Alan Turing',
        'Mark Weiser',
        'Steve Jobs',
        'Bill Gates',
      ],
      correct: 2,
    },
    {
      id: 124,
      text: 'Which research lab is known for advancing ubiquitous computing?',
      options: [
        'MIT Media Lab',
        'Microsoft Research',
        'Xerox PARC',
        'IBM Watson Lab',
      ],
      correct: 3,
    },
    {
      id: 125,
      text: 'What is the focus of "Things That Think" research at MIT?',
      options: [
        'Desktop software development',
        'Wearable computing and smart objects',
        'Network security',
        'Data analytics',
      ],
      correct: 2,
    },
    {
      id: 126,
      text: 'Which concept envisions environments that adapt to user needs automatically?',
      options: [
        'Attentive environments',
        'Virtual environments',
        'Cloud storage',
        'Blockchain technology',
      ],
      correct: 1,
    },
    {
      id: 127,
      text: 'What is the term used to describe tangible, interactive objects embedded with technology?',
      options: [
        'Augmented objects',
        'Tangible bits',
        'Virtual devices',
        'Digital assistants',
      ],
      correct: 2,
    },
    {
      id: 128,
      text: 'Which field focuses on integrating physical objects with digital information?',
      options: [
        'Pervasive computing',
        'Tangible media',
        'Networking',
        'System administration',
      ],
      correct: 2,
    },
    {
      id: 129,
      text: 'Who coined the term "Everyware" to describe ubiquitous computing technologies?',
      options: [
        'Adam Greenfield',
        'Alan Kay',
        'Douglas Engelbart',
        'John McCarthy',
      ],
      correct: 1,
    },
    {
      id: 130,
      text: 'Which term refers to the interaction of computers in everyday environments without user awareness?',
      options: [
        'Augmented reality',
        'Silent computing',
        'Pervasive computing',
        'Quantum computing',
      ],
      correct: 3,
    },
    {
      id: 131,
      text: 'What is the goal of accessible web design?',
      options: [
        'To focus solely on visual design',
        'To ensure usability for all users, including those with disabilities',
        'To limit content for faster performance',
        'To enhance site advertisements',
      ],
      correct: 2,
    },
    {
      id: 132,
      text: 'Which organization’s guidelines are commonly referenced for web accessibility?',
      options: [
        'IEEE',
        'ISO',
        'W3C',
        'FCC',
      ],
      correct: 3,
    },
    {
      id: 133,
      text: 'Which factor is crucial for ensuring accessibility in web design?',
      options: [
        'Complex navigation',
        'Contrast and readability',
        'Decorative images',
        'Minimal text',
      ],
      correct: 2,
    },
    {
      id: 134,
      text: 'Which term describes the practice of designing web content usable by people with diverse abilities?',
      options: [
        'Responsive design',
        'Accessible design',
        'Adaptive design',
        'Progressive design',
      ],
      correct: 2,
    },
    {
      id: 135,
      text: 'Why is web accessibility important?',
      options: [
        'It reduces website development costs',
        'It increases legal compliance and inclusivity',
        'It maximizes advertisements',
        'It improves system performance',
      ],
      correct: 2,
    },
    {
      id: 136,
      text: 'Which feedback mechanism assists users without disrupting their workflow?',
      options: [
        'Modal dialogs',
        'Pop-ups',
        'Modeless feedback',
        'Push notifications',
      ],
      correct: 3,
    },
    {
      id: 137,
      text: 'Which feature enhances information retrieval in large-scale websites?',
      options: [
        'Animated banners',
        'Controlled vocabularies and metadata',
        'Complex URLs',
        'Pop-up menus',
      ],
      correct: 2,
    },
    {
      id: 138,
      text: 'Which type of metadata improves search engine optimization (SEO)?',
      options: [
        'Descriptive keywords and meta tags',
        'File extension labels',
        'Version numbers',
        'Randomly generated text',
      ],
      correct: 1,
    },
    {
      id: 139,
      text: 'Which technology trend represents the future of computing environments?',
      options: [
        'Centralized computing',
        'Pervasive and ubiquitous computing',
        'Desktop-only interfaces',
        'Command-line interfaces',
      ],
      correct: 2,
    },
    {
      id: 140,
      text: 'What is a key benefit of integrating ambient informatics into daily environments?',
      options: [
        'Faster internet speeds',
        'Seamless user interaction with minimal effort',
        'More manual configurations',
        'Increased system errors',
      ],
      correct: 2,
    },
  ];
              