export const it430 = [
    {
      id: 1,
      text: 'What is the primary function of Enterprise Resource Planning (ERP)?',
      options: [
        'To manage only financial data',
        'To integrate all aspects of a business',
        'To handle only supply chain management',
        'To replace the need for customer data',
      ],
      correct: 2,
    },
    {
      id: 2,
      text: 'Which software helps gather data from customer activities for analysis?',
      options: [
        'Firewall Software',
        'Cryptography Software',
        'Customer Relationship Management (CRM) Software',
        'Digital Signature Software',
      ],
      correct: 3,
    },
    {
      id: 3,
      text: 'Which software deals with the management and flow of goods from raw material to the finished stage?',
      options: [
        'Firewall Software',
        'Supply Chain Management (SCM) Software',
        'ERP Software',
        'Digital Signature Software',
      ],
      correct: 2,
    },
    {
      id: 4,
      text: 'What does Content Management Software primarily help with?',
      options: [
        'Protecting internal networks from threats',
        'Managing and controlling corporate information',
        'Encrypting customer data',
        'Facilitating financial transactions',
      ],
      correct: 2,
    },
    {
      id: 5,
      text: 'What is the main goal of a Firewall?',
      options: [
        'To monitor financial transactions',
        'To protect a network from external threats',
        'To store customer data',
        'To manage e-commerce websites',
      ],
      correct: 2,
    },
    {
      id: 6,
      text: 'Which type of firewall operates at the transport layer of the OSI model?',
      options: [
        'Packet Filter Firewall',
        'Circuit Level Firewall',
        'Application Gateway Firewall',
        'Proxy Firewall',
      ],
      correct: 2,
    },
    {
      id: 7,
      text: 'Which layer does an Application Gateway Firewall operate at?',
      options: [
        'Network Layer',
        'Data Link Layer',
        'Application Layer',
        'Transport Layer',
      ],
      correct: 3,
    },
    {
      id: 8,
      text: 'Which process involves scrambling a message using a key?',
      options: [
        'Decryption',
        'Hashing',
        'Encryption',
        'Certification',
      ],
      correct: 3,
    },
    {
      id: 9,
      text: 'In asymmetric cryptography, what is used to decrypt a message?',
      options: [
        'The same key used for encryption',
        'A public key',
        'A private key',
        'A password',
      ],
      correct: 3,
    },
    {
      id: 10,
      text: 'What is the primary purpose of a digital signature?',
      options: [
        'To encrypt messages',
        'To authenticate and ensure integrity of electronic documents',
        'To manage content on websites',
        'To monitor web traffic',
      ],
      correct: 2,
    },
    {
      id: 11,
      text: 'Which organization is a leading certification authority (CA)?',
      options: [
        'Microsoft',
        'Verisign',
        'IBM',
        'Google',
      ],
      correct: 2,
    },
    {
      id: 12,
      text: 'What is the result of applying a hash function to a message?',
      options: [
        'A digital certificate',
        'A message digest',
        'A public key',
        'An encrypted message',
      ],
      correct: 2,
    },
    {
      id: 13,
      text: 'Which term describes the process of converting a readable message into an unintelligible form?',
      options: [
        'Decryption',
        'Encoding',
        'Encryption',
        'Signing',
      ],
      correct: 3,
    },
    {
      id: 14,
      text: 'Which encryption method uses the same key for encryption and decryption?',
      options: [
        'Asymmetric Cryptography',
        'Symmetric Cryptography',
        'Hashing',
        'Digital Signatures',
      ],
      correct: 2,
    },
    {
      id: 15,
      text: 'What is the main role of a Certification Authority (CA)?',
      options: [
        'To encrypt messages',
        'To issue digital certificates',
        'To manage ERP systems',
        'To perform cryptographic attacks',
      ],
      correct: 2,
    },
    {
      id: 16,
      text: 'Which type of software manages large sets of corporate data and files?',
      options: [
        'Firewall Software',
        'Content Management Software',
        'Digital Signature Software',
        'Encryption Software',
      ],
      correct: 2,
    },
    {
      id: 17,
      text: 'What ensures that a digital message has not been altered during transmission?',
      options: [
        'Encryption',
        'Message Digest',
        'Firewall',
        'ERP System',
      ],
      correct: 2,
    },
    {
      id: 18,
      text: 'Which component is essential for e-cash systems to ensure the anonymity of transactions?',
      options: [
        'Public Key',
        'Symmetric Key',
        'Digital Certificates',
        'Cyber Wallet',
      ],
      correct: 4,
    },
    {
      id: 19,
      text: 'Which encryption method uses different keys for encryption and decryption?',
      options: [
        'Symmetric Encryption',
        'Asymmetric Encryption',
        'Hashing',
        'Content Management',
      ],
      correct: 2,
    },
    {
      id: 20,
      text: 'Which component verifies the authenticity of a public key?',
      options: [
        'Digital Certificate',
        'Message Digest',
        'Hash Function',
        'Symmetric Key',
      ],
      correct: 1,
    },
    {
      id: 21,
      text: 'Which of the following is a popular symmetric key algorithm?',
      options: [
        'RSA',
        'DES',
        'Elliptic Curve',
        'Diffie-Hellman',
      ],
      correct: 2,
    },
    {
      id: 22,
      text: 'Which attack attempts to decrypt messages by trying every possible key?',
      options: [
        'Cryptanalysis',
        'System Attack',
        'Brute Force Attack',
        'SQL Injection',
      ],
      correct: 3,
    },
    {
      id: 23,
      text: 'What is the key length of the Data Encryption Standard (DES)?',
      options: [
        '56 bits',
        '128 bits',
        '192 bits',
        '256 bits',
      ],
      correct: 1,
    },
    {
      id: 24,
      text: 'Which symmetric key algorithm uses a variable key length between 1 to 2048 bits?',
      options: [
        'RC2',
        'RSA',
        'DSA',
        'SHA-256',
      ],
      correct: 1,
    },
    {
      id: 25,
      text: 'In a Virtual PIN Payment System, what does the buyer provide to the merchant?',
      options: [
        'Public Key',
        'Account Number',
        'Virtual PIN',
        'Bank Statement',
      ],
      correct: 3,
    },
    {
      id: 26,
      text: 'Who verifies the Virtual PIN during a transaction in a Virtual PIN Payment System?',
      options: [
        'Merchant',
        'Client Browser',
        'E-cash Bank',
        'Internet Payment System Server',
      ],
      correct: 4,
    },
    {
      id: 27,
      text: 'What happens if a Virtual PIN is blacklisted?',
      options: [
        'Transaction is declined',
        'PIN is reset',
        'Partial payment is allowed',
        'Merchant accepts the transaction',
      ],
      correct: 1,
    },
    {
      id: 28,
      text: 'Which element is crucial in e-cash systems for verifying the legitimacy of coins?',
      options: [
        'Merchant Signature',
        'Serial Number',
        'Client Password',
        'Firewall',
      ],
      correct: 2,
    },
    {
      id: 29,
      text: 'What is stored in the client’s cyber wallet in e-cash systems?',
      options: [
        'Bank Account Numbers',
        'E-cash Coins',
        'Merchant Data',
        'Passwords',
      ],
      correct: 2,
    },
    {
      id: 30,
      text: 'How does the e-cash bank verify that e-cash coins are not already spent?',
      options: [
        'By encrypting the coins',
        'By comparing serial numbers with its database',
        'By using firewalls',
        'By hashing the transaction',
      ],
      correct: 2,
    },
    {
      id: 31,
      text: 'Which protocol is commonly used for secure online transactions?',
      options: [
        'HTTP',
        'FTP',
        'SSL',
        'SMTP',
      ],
      correct: 3,
    },
    {
      id: 32,
      text: 'What does SSL stand for in online payment security?',
      options: [
        'Secure Scripting Language',
        'Secure Socket Layer',
        'System Socket Link',
        'System Security Layer',
      ],
      correct: 2,
    },
    {
      id: 33,
      text: 'Which combination of cryptography does SSL use?',
      options: [
        'Symmetric only',
        'Asymmetric only',
        'Symmetric and Asymmetric',
        'Hashing only',
      ],
      correct: 3,
    },
    {
      id: 34,
      text: 'What is indicated when a URL begins with “https”?',
      options: [
        'The site uses FTP',
        'The connection is SSL encrypted',
        'The website is public',
        'Cookies are disabled',
      ],
      correct: 2,
    },
    {
      id: 35,
      text: 'What part of SSL encryption is responsible for generating a session key?',
      options: [
        'Client Browser',
        'Merchant',
        'Certificate Authority',
        'Firewall',
      ],
      correct: 1,
    },
    {
      id: 36,
      text: 'Which organization typically issues digital certificates used in SSL?',
      options: [
        'Verisign',
        'Google',
        'Mozilla',
        'PayPal',
      ],
      correct: 1,
    },
    {
      id: 37,
      text: 'In e-cash systems, what prevents merchants from viewing coin details?',
      options: [
        'Encryption by the e-cash bank',
        'Digital Signature',
        'Hashing',
        'Merchant Firewall',
      ],
      correct: 1,
    },
    {
      id: 38,
      text: 'What technology ensures secure communication between the client and server?',
      options: [
        'VPN',
        'Firewall',
        'SSL',
        'Router',
      ],
      correct: 3,
    },
    {
      id: 39,
      text: 'What component generates serial numbers for coins in e-cash systems?',
      options: [
        'Merchant Software',
        'Cyber Wallet',
        'Firewall',
        'SSL',
      ],
      correct: 2,
    },
    {
      id: 40,
      text: 'Which of the following is a potential weakness of SSL?',
      options: [
        'Complex installation process',
        'Lack of encryption support',
        'Merchant can store decrypted credit card data',
        'No support for digital certificates',
      ],
      correct: 3,
    },
    {
      id: 41,
      text: 'What does SSL stand for in terms of online security?',
      options: [
        'Simple Scripting Language',
        'Secure Socket Layer',
        'System Security Layer',
        'Secure System Link',
      ],
      correct: 2,
    },
    {
      id: 42,
      text: 'Which type of cryptography is used in SSL for session encryption?',
      options: [
        'Symmetric',
        'Asymmetric',
        'Hashing',
        'Elliptic Curve',
      ],
      correct: 1,
    },
    {
      id: 43,
      text: 'What is the first step in an SSL handshake?',
      options: [
        'Server sends public key',
        'Client sends "hello" message',
        'Session key is generated',
        'Digital certificate is verified',
      ],
      correct: 2,
    },
    {
      id: 44,
      text: 'Which entity issues the digital certificates used in SSL communication?',
      options: [
        'Banks',
        'Certificate Authorities',
        'SSL Clients',
        'Firewall Administrators',
      ],
      correct: 2,
    },
    {
      id: 45,
      text: 'What is the main disadvantage of SSL for credit card payments?',
      options: [
        'It is difficult to configure',
        'Encryption fails on large data',
        'Merchant stores decrypted credit card data',
        'Requires specialized hardware',
      ],
      correct: 3,
    },
    {
      id: 46,
      text: 'Which protocol was developed to address SSL’s limitations in online payments?',
      options: [
        'VPN',
        'SSH',
        'SET (Secure Electronic Transaction)',
        'SMTP',
      ],
      correct: 3,
    },
    {
      id: 47,
      text: 'What is the primary focus of e-business?',
      options: [
        'Website design',
        'Online marketing',
        'Improving operational efficiency and generating revenue',
        'Building mobile applications',
      ],
      correct: 3,
    },
    {
      id: 48,
      text: 'Which e-business revenue model relies on online advertisements for income?',
      options: [
        'Digital Content Model',
        'Fee-for-Service Model',
        'Advertising-Supported Model',
        'Web Catalogue Model',
      ],
      correct: 3,
    },
    {
      id: 49,
      text: 'Which of the following is an example of a digital content revenue model?',
      options: [
        'Online Newspaper Subscription',
        'Travel Booking Website',
        'Online Clothing Store',
        'E-learning Platforms',
      ],
      correct: 1,
    },
    {
      id: 50,
      text: 'In the fee-for-transaction revenue model, revenue is generated by:',
      options: [
        'Selling physical products online',
        'Charging for each transaction processed',
        'Offering free content',
        'Running advertisements',
      ],
      correct: 2,
    },
    {
      id: 51,
      text: 'Which type of e-business model involves professional services provided directly to users?',
      options: [
        'Fee-for-Service Model',
        'Web Catalogue Model',
        'Advertising-Subscription Model',
        'Digital Content Model',
      ],
      correct: 1,
    },
    {
      id: 52,
      text: 'What distinguishes e-business from e-commerce?',
      options: [
        'E-business covers broader activities beyond buying and selling',
        'E-commerce deals only with physical products',
        'E-business does not require an internet connection',
        'E-commerce focuses on in-person transactions',
      ],
      correct: 1,
    },
    {
      id: 53,
      text: 'Which marketing method uses automated email systems to engage with customers?',
      options: [
        'Social Media Marketing',
        'Telemarketing',
        'E-mail Marketing',
        'Search Engine Optimization (SEO)',
      ],
      correct: 3,
    },
    {
      id: 54,
      text: 'In email marketing, what is the primary goal of segmentation?',
      options: [
        'To reduce the number of emails sent',
        'To send targeted emails to specific groups',
        'To track customer behavior',
        'To increase server speed',
      ],
      correct: 2,
    },
    {
      id: 55,
      text: 'What is a key advantage of email marketing over traditional marketing?',
      options: [
        'Higher cost',
        'Lower reach',
        'Direct interaction with customers at low cost',
        'Requires physical presence',
      ],
      correct: 3,
    },
    {
      id: 56,
      text: 'What should be included in an effective marketing email subject line?',
      options: [
        'Lengthy details',
        'Clickbait text',
        'Clear, concise, and relevant content',
        'Complex language',
      ],
      correct: 3,
    },
    {
      id: 57,
      text: 'Which is a potential disadvantage of e-business?',
      options: [
        'Higher transaction speed',
        'Lack of face-to-face interaction',
        'Global reach',
        'Cost savings on physical infrastructure',
      ],
      correct: 2,
    },
    {
      id: 58,
      text: 'Which of the following helps secure email marketing campaigns?',
      options: [
        'Using SSL encryption',
        'Avoiding personalized content',
        'Adding lengthy attachments',
        'Ignoring unsubscribe requests',
      ],
      correct: 1,
    },
    {
      id: 59,
      text: 'Which e-business model allows customers to purchase from multiple vendors through one platform?',
      options: [
        'Online Shopping Mall',
        'Digital Library',
        'Single Vendor Site',
        'Fee-for-Service',
      ],
      correct: 1,
    },
    {
      id: 60,
      text: 'Which is an example of a horizontal portal in e-business?',
      options: [
        'Online Banking Site',
        'Medical Community Portal',
        'Yahoo Search Engine',
        'E-learning Portal',
      ],
      correct: 3,
    },
    {
      id: 61,
      text: 'What is the main goal of Customer Relationship Management (CRM)?',
      options: [
        'To secure e-commerce websites',
        'To manage customer data and enhance relationships',
        'To encrypt sensitive information',
        'To create firewalls for network security',
      ],
      correct: 2,
    },
    {
      id: 62,
      text: 'Which component is crucial for effective CRM systems?',
      options: [
        'Web servers',
        'Customer data',
        'Firewall',
        'Digital certificates',
      ],
      correct: 2,
    },
    {
      id: 63,
      text: 'Which term describes additional information about data that helps in categorizing it?',
      options: [
        'Metadata',
        'Algorithm',
        'Encryption key',
        'Hash function',
      ],
      correct: 1,
    },
    {
      id: 64,
      text: 'What is the primary purpose of metadata in databases?',
      options: [
        'To store customer addresses',
        'To encrypt data',
        'To describe and organize data',
        'To create SSL certificates',
      ],
      correct: 3,
    },
    {
      id: 65,
      text: 'Which technique is used to discover patterns in large sets of data?',
      options: [
        'Firewall management',
        'Data mining',
        'SSL encryption',
        'Digital signature',
      ],
      correct: 2,
    },
    {
      id: 66,
      text: 'What does the term "confidence" measure in data mining?',
      options: [
        'The percentage of secure transactions',
        'The strength of association between items',
        'The speed of database queries',
        'The efficiency of firewalls',
      ],
      correct: 2,
    },
    {
      id: 67,
      text: 'In data mining, what is "support"?',
      options: [
        'The percentage of overall transactions containing a specific combination of items',
        'The financial backing for a project',
        'The level of customer engagement',
        'The total encrypted files in a database',
      ],
      correct: 1,
    },
    {
      id: 68,
      text: 'What is the role of data warehouses in data mining?',
      options: [
        'To provide network security',
        'To store large amounts of data for analysis',
        'To encrypt digital messages',
        'To manage SSL certificates',
      ],
      correct: 2,
    },
    {
      id: 69,
      text: 'Which of the following is a key advantage of data mining for businesses?',
      options: [
        'Higher costs of operations',
        'Discovering hidden patterns and trends',
        'Slower data retrieval',
        'Limited access to customer information',
      ],
      correct: 2,
    },
    {
      id: 70,
      text: 'Which algorithm is commonly used for association mining?',
      options: [
        'DES',
        'Apriori',
        'AES',
        'SHA-256',
      ],
      correct: 2,
    },
    {
      id: 71,
      text: 'Which process involves extracting useful knowledge from large data sets?',
      options: [
        'Firewall setup',
        'Data mining',
        'VPN configuration',
        'SSL handshake',
      ],
      correct: 2,
    },
    {
      id: 72,
      text: 'Which of the following best describes "data characterization"?',
      options: [
        'Discovering general patterns in data',
        'Encrypting digital signatures',
        'Establishing SSL connections',
        'Installing firewalls',
      ],
      correct: 1,
    },
    {
      id: 73,
      text: 'Which tool is commonly used for Online Analytical Processing (OLAP)?',
      options: [
        'Data cube',
        'Firewall',
        'Digital certificate',
        'Hash function',
      ],
      correct: 1,
    },
    {
      id: 74,
      text: 'Which technique helps businesses predict customer behavior through data analysis?',
      options: [
        'VPN',
        'Firewall',
        'Data mining',
        'Digital signature',
      ],
      correct: 3,
    },
    {
      id: 75,
      text: 'What is the outcome of the "association" process in data mining?',
      options: [
        'Identifying relationships between data items',
        'Creating SSL keys',
        'Developing firewalls',
        'Encrypting data',
      ],
      correct: 1,
    },
    {
      id: 76,
      text: 'Which visualization method is used in OLAP to represent data in multiple dimensions?',
      options: [
        'Data cube',
        'Firewall logs',
        'SSL certificates',
        'Metadata graphs',
      ],
      correct: 1,
    },
    {
      id: 77,
      text: 'Which factor determines the strength of a rule in association mining?',
      options: [
        'Confidence',
        'Latency',
        'Encryption speed',
        'Data type',
      ],
      correct: 1,
    },
    {
      id: 78,
      text: 'What role does metadata play in data management?',
      options: [
        'It describes data attributes and structure',
        'It encrypts data',
        'It verifies SSL connections',
        'It blocks malware',
      ],
      correct: 1,
    },
    {
      id: 79,
      text: 'Which component is essential for building data warehouses?',
      options: [
        'Data transformation and integration',
        'Firewall software',
        'SSL protocol',
        'Email server',
      ],
      correct: 1,
    },
    {
      id: 80,
      text: 'What is the purpose of Online Analytical Processing (OLAP)?',
      options: [
        'To perform real-time transaction encryption',
        'To analyze complex data interactively',
        'To manage digital certificates',
        'To block unauthorized access to websites',
      ],
      correct: 2,
    },
    {
      id: 81,
      text: 'What is the primary purpose of Electronic Data Interchange (EDI)?',
      options: [
        'To encrypt customer data',
        'To facilitate secure email communication',
        'To exchange business documents electronically',
        'To manage database records',
      ],
      correct: 3,
    },
    {
      id: 82,
      text: 'Which of the following is an example of EDI application?',
      options: [
        'Online video streaming',
        'Automated stock trading',
        'Electronic invoicing',
        'Web development',
      ],
      correct: 3,
    },
    {
      id: 83,
      text: 'What is a key benefit of EDI in supply chain management?',
      options: [
        'Increased paperwork',
        'Slower transactions',
        'Faster and more accurate transactions',
        'Higher transaction costs',
      ],
      correct: 3,
    },
    {
      id: 84,
      text: 'Which software is commonly used for personal finance management online?',
      options: [
        'Quicken',
        'Apache',
        'MS Access',
        'Photoshop',
      ],
      correct: 1,
    },
    {
      id: 85,
      text: 'What is the role of personal finance software like Quicken?',
      options: [
        'To manage databases',
        'To track and manage personal expenses',
        'To encrypt online transactions',
        'To perform virus scans',
      ],
      correct: 2,
    },
    {
      id: 86,
      text: 'Which process is used to manage and automate financial transactions online?',
      options: [
        'Firewall configuration',
        'EDI',
        'Cloud computing',
        'Personal Finance Management',
      ],
      correct: 4,
    },
    {
      id: 87,
      text: 'What is the key purpose of supply chain management?',
      options: [
        'To encrypt customer records',
        'To manage the flow of goods and services',
        'To design customer websites',
        'To create marketing campaigns',
      ],
      correct: 2,
    },
    {
      id: 88,
      text: 'Which of the following is a key component of supply chain management?',
      options: [
        'Content marketing',
        'Product development',
        'Inventory management',
        'Customer surveys',
      ],
      correct: 3,
    },
    {
      id: 89,
      text: 'Which concept focuses on reducing costs and increasing efficiency in supply chain processes?',
      options: [
        'Value chain analysis',
        'Email marketing',
        'Digital advertising',
        'SEO optimization',
      ],
      correct: 1,
    },
    {
      id: 90,
      text: 'Who developed the concept of the value chain?',
      options: [
        'Bill Gates',
        'Michael Porter',
        'Elon Musk',
        'Jeff Bezos',
      ],
      correct: 2,
    },
    {
      id: 91,
      text: 'What is the goal of Porter’s model of competitive rivalry?',
      options: [
        'To improve software coding practices',
        'To analyze competition and improve strategic positioning',
        'To manage supply chain logistics',
        'To develop encryption standards',
      ],
      correct: 2,
    },
    {
      id: 92,
      text: 'Which element is part of Porter’s Five Forces model?',
      options: [
        'Data encryption',
        'Supplier power',
        'Website design',
        'Email segmentation',
      ],
      correct: 2,
    },
    {
      id: 93,
      text: 'Which force in Porter’s model relates to the threat of new companies entering the market?',
      options: [
        'Bargaining power of buyers',
        'Threat of substitutes',
        'Threat of new entrants',
        'Industry rivalry',
      ],
      correct: 3,
    },
    {
      id: 94,
      text: 'Which activity is considered a primary activity in the value chain?',
      options: [
        'Marketing and sales',
        'Human resource management',
        'Technology development',
        'Procurement',
      ],
      correct: 1,
    },
    {
      id: 95,
      text: 'What is the focus of after-sales services in the value chain?',
      options: [
        'Increasing product cost',
        'Ensuring customer satisfaction and product support',
        'Hiring new staff',
        'Managing email marketing campaigns',
      ],
      correct: 2,
    },
    {
      id: 96,
      text: 'Which type of activity supports primary activities in the value chain?',
      options: [
        'Sales promotions',
        'Operations',
        'Technology development',
        'Outbound logistics',
      ],
      correct: 3,
    },
    {
      id: 97,
      text: 'Which activity in Porter’s model focuses on finding and serving new customers?',
      options: [
        'Procurement',
        'Identify customers',
        'Manufacturing',
        'Inventory management',
      ],
      correct: 2,
    },
    {
      id: 98,
      text: 'What is the main objective of procurement in the value chain?',
      options: [
        'Hiring new staff',
        'Purchasing materials and supplies',
        'Conducting market surveys',
        'Running advertisements',
      ],
      correct: 2,
    },
    {
      id: 99,
      text: 'Which value chain activity involves transforming raw materials into finished products?',
      options: [
        'Inbound logistics',
        'Marketing and sales',
        'Operations',
        'Procurement',
      ],
      correct: 3,
    },
    {
      id: 100,
      text: 'Which force in Porter’s Five Forces model represents the intensity of competition among existing players?',
      options: [
        'Threat of substitutes',
        'Industry rivalry',
        'Bargaining power of suppliers',
        'Buyer demand',
      ],
      correct: 2,
    },
    {
      id: 101,
      text: 'Which of the following is a significant barrier to international e-commerce?',
      options: [
        'Lack of product variety',
        'Different legal and regulatory environments',
        'Low internet penetration',
        'Limited online advertising',
      ],
      correct: 2,
    },
    {
      id: 102,
      text: 'Which ordinance in Pakistan governs electronic transactions?',
      options: [
        'Data Protection Act',
        'Electronic Transactions Ordinance (ETO), 2002',
        'Cyber Security Act',
        'Consumer Protection Act',
      ],
      correct: 2,
    },
    {
      id: 103,
      text: 'What is the primary objective of the Electronic Transactions Ordinance (ETO)?',
      options: [
        'To restrict online transactions',
        'To promote electronic communication and e-commerce',
        'To regulate internet usage',
        'To limit the use of credit cards online',
      ],
      correct: 2,
    },
    {
      id: 104,
      text: 'Which section of the ETO recognizes electronic documents as legally valid?',
      options: [
        'Section 3',
        'Section 10',
        'Section 17',
        'Section 25',
      ],
      correct: 1,
    },
    {
      id: 105,
      text: 'Which legal issue arises when determining jurisdiction in international e-commerce?',
      options: [
        'Intellectual property',
        'Territorial jurisdiction',
        'Language barriers',
        'Lack of internet access',
      ],
      correct: 2,
    },
    {
      id: 106,
      text: 'Which organization proposed the model law on e-commerce in 1996?',
      options: [
        'World Trade Organization (WTO)',
        'United Nations Commission on International Trade Law (UNCITRAL)',
        'International Monetary Fund (IMF)',
        'World Bank',
      ],
      correct: 2,
    },
    {
      id: 107,
      text: 'Which of the following is a common issue in global e-commerce?',
      options: [
        'Taxation of online transactions',
        'Ease of logistics management',
        'Unlimited customer base',
        'Guaranteed profit margins',
      ],
      correct: 1,
    },
    {
      id: 108,
      text: 'Which legal concept protects domain names from being hijacked?',
      options: [
        'Copyright Law',
        'Trademark Law',
        'Patent Law',
        'Contract Law',
      ],
      correct: 2,
    },
    {
      id: 109,
      text: 'Which international issue can arise due to the distribution of digital content?',
      options: [
        'Online fraud',
        'Copyright infringement',
        'Language translation',
        'Product packaging',
      ],
      correct: 2,
    },
    {
      id: 110,
      text: 'What type of cyber crime involves unauthorized access to a computer system?',
      options: [
        'Cyberstalking',
        'Hacking',
        'Online defamation',
        'Spam',
      ],
      correct: 2,
    },
    {
      id: 111,
      text: 'What legal issue concerns misleading statements made online about another person or company?',
      options: [
        'Domain name conflict',
        'Online defamation',
        'Patent infringement',
        'Phishing',
      ],
      correct: 2,
    },
    {
      id: 112,
      text: 'Which of the following is considered an online contract?',
      options: [
        'Physical handshake agreement',
        'Verbal communication over the phone',
        'Click-wrap agreement',
        'Signed paper document',
      ],
      correct: 3,
    },
    {
      id: 113,
      text: 'Which of the following laws addresses privacy concerns in online transactions?',
      options: [
        'Electronic Transactions Ordinance (ETO)',
        'Data Protection Law',
        'Tax Ordinance',
        'Copyright Act',
      ],
      correct: 2,
    },
    {
      id: 114,
      text: 'Which legal principle allows electronic signatures to be treated as valid in Pakistan?',
      options: [
        'Section 10 of ETO',
        'Section 6 of ETO',
        'Section 3 of ETO',
        'Section 15 of ETO',
      ],
      correct: 3,
    },
    {
      id: 115,
      text: 'Which legal issue deals with conflicts over website domain names?',
      options: [
        'Patent Law',
        'Online Defamation',
        'Domain name and trademark conflicts',
        'Spam Law',
      ],
      correct: 3,
    },
    {
      id: 116,
      text: 'What type of online fraud involves sending fake emails to obtain sensitive information?',
      options: [
        'Cyberstalking',
        'Phishing',
        'Online hate',
        'Eavesdropping',
      ],
      correct: 2,
    },
    {
      id: 117,
      text: 'Which court in Pakistan has jurisdiction to handle ETO-related cases?',
      options: [
        'Civil Court',
        'Session Court',
        'District Court',
        'High Court',
      ],
      correct: 2,
    },
    {
      id: 118,
      text: 'What is the primary focus of international e-commerce law?',
      options: [
        'Controlling internet prices',
        'Regulating cyber cafes',
        'Facilitating cross-border transactions',
        'Monitoring online forums',
      ],
      correct: 3,
    },
    {
      id: 119,
      text: 'Which type of tax applies to e-commerce businesses operating across borders?',
      options: [
        'Property Tax',
        'Value Added Tax (VAT)',
        'Corporate Tax',
        'Excise Duty',
      ],
      correct: 2,
    },
    {
      id: 120,
      text: 'Which legal issue is associated with online privacy and data protection?',
      options: [
        'Copyright infringement',
        'Identity theft',
        'Trademark violation',
        'Patent disputes',
      ],
      correct: 2,
    },
  ];
  
  